export const Data = [
  {
    id: 1,
    image: require("./assets/img/inspiration1.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 2,
    image: require("./assets/img/inspiration2.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 3,
    image: require("./assets/img/inspiration3.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 4,
    image: require("./assets/img/inspiration4.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 5,
    image: require("./assets/img/inspiration5.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 6,
    image: require("./assets/img/inspiration6.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 7,
    image: require("./assets/img/inspiration7.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 8,
    image: require("./assets/img/inspiration8.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 9,
    image: require("./assets/img/inspiration1.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 10,
    image: require("./assets/img/inspiration2.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 11,
    image: require("./assets/img/inspiration3.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 12,
    image: require("./assets/img/inspiration4.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 13,
    image: require("./assets/img/inspiration5.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 14,
    image: require("./assets/img/inspiration6.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 15,
    image: require("./assets/img/inspiration7.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
  {
    id: 16,
    image: require("./assets/img/inspiration8.png"),
    title1: "Desert king",
    title2: "1MBT per night",
    title3: "2345km away",
    title4: "available for 2weeks stay",
    icon: require("./assets/img/starIcon.png"),
  },
];

export default Data;

export const Data2 = [];
